src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/java/org/jenkinsci/plugins/prometheus/rest/PrometheusAction.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/Messages.properties
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-path.jelly

The PR will add the following new features to the plugin:
1. add possibility to configure the plugin within the global settings of the Jenkins not via an environment variable
2. allow slashes in the prometheus endpoint path
3. add possibility to enable authentication for the prometheus endpoint

Allow slashes in path and add authentication for the metrics endpoint

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

I implemented a few metrics for jobs based on what the [InfluxDB plugins has](https://wiki.jenkins.io/display/JENKINS/InfluxDB+Plugin).
This will add this metrics:
* _last_build_result_ordinal
* _last_build_result
* _last_build_duration_milliseconds
* _last_build_score
* _last_build_tests_total
* _last_build_tests_skipped
* _last_build_tests_failing

Add extra job metrics

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-path.jelly

There is no need to take in account / send metrics about disable jobs.
If this options is enable the values of *_duration_milliseconds_summary* will have a "bump"

Add option to process or ignore disabled jobs.

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-path.jelly

Use case:
We have a Jenkins with almost 2k jobs. When Prometheus plugin is collecting the test results of the builds, the scarped JSON will grow by approx. 6k lines.
Thus I made the fetching of build test results configurable.

Allow to configure fetching of test results from builds

---

pom.xml
src/test/java/org/jenkinsci/plugins/prometheus/util/FlowNodesTest.java

This was developed alongside #47 to validate the abort works when it encounters something that is already in the list

Adding a basic unit test to show that the abort works

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

In order to present a dashboard on Grafana for the number of builds per Source control repository, we need a way to group all branches and Pull Request with an identifier (the repository name).
If you are using multi-branch or Github organization Job the jobs names will be [Organization/Repository/Branch],
In order to group them into one counter, Grafana requires the repository name.
This change adds the repository name as an attribute and allows the display of builds per repository.

Adding a way to group jobs by source control repo

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

This PR fixes the issue #65 .
Now the jobs will not get looked at if you don't want to expose any metrics from them.
This hugely increases performance on large instances.
Please let me know, if you need any additions or if you have any remarks,.

Ignoring build metrics

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/rest/PrometheusAction.java

Add in Prometheus default java metric exports. Includes metrics for garbage collection, memory pools, JMX, classloading, and thread counts. Useful as it uses the standard java metric names allowing generic jvm alert rules to be used against the Jenkins Prometheus plugin. 
See -- https://github.com/prometheus/client_java#included-collectors
In summary add the following metrics:
```
jvm_classes_loaded
jvm_classes_loaded_total
jvm_classes_unloaded_total
jvm_gc_collection_seconds_count
jvm_gc_collection_seconds_count
jvm_gc_collection_seconds_sum
jvm_gc_collection_seconds_sum
jvm_info
jvm_memory_bytes_committed
jvm_memory_bytes_committed
jvm_memory_bytes_max
jvm_memory_bytes_max
jvm_memory_bytes_used
jvm_memory_bytes_used
jvm_memory_pool_bytes_committed
jvm_memory_pool_bytes_committed …
```

Add in Prometheus default java metric exports.

---

pom.xml

Updating java_client to v0.6.0 adds the following new DefaultExports. 
```
jvm_threads_state{state="BLOCKED"}                                                                                      
jvm_threads_state{state="NEW"}                                                                                          
jvm_threads_state{state="RUNNABLE"}                                                                                     
jvm_threads_state{state="TERMINATED"}                                                                                   
jvm_threads_state{state="TIMED_WAITING"}                                                                                
jvm_threads_state{state="WAITING"} …
```

Update java_client to latest 0.6.0 release

---

src/main/java/org/jenkinsci/plugins/prometheus/MetricsRequest.java

This change adds a `Cache-Control` header on the endpoint so that reverse proxies and load balancers in front of Jenkins do not cache metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/prometheus-plugin/96)

Cache-Control on Prometheus endpoint

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/DiskUsageCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java
src/main/java/org/jenkinsci/plugins/prometheus/util/ConfigurationUtils.java

Adding these new metrics
```
default_jenkins_disk_usage{directory="java.io.tmpdir",} 8.5937152E7
default_jenkins_disk_usage{directory="JENKINS_HOME",} 3.7107712E7
default_jenkins_disk_usage{directory="JENKINS_HOME/secrets",} 3072.0
default_jenkins_disk_usage{directory="JENKINS_HOME/users",} 0.0
default_jenkins_disk_usage{directory="JENKINS_HOME/jobs",} 0.0
default_jenkins_disk_usage{directory="JENKINS_HOME/nodes",} 0.0
default_jenkins_disk_usage{directory="JENKINS_HOME/plugins",} 3.7100544E7
default_jenkins_job_usage{jobName="Folder_1/job-1",url="job/Folder_1/job/job-1/",} 282000.0
```

Adding disk usage metrics

---

src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java

The original algorithm aborted the traversal if ANY visited nodes were detected, but this wasn't carried over in the original refactor. This fixes this in the original traverseTree function as well.

Fixing bug in traversal algorithm.

---

src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java

When the switch to iterative BFS was made, adding to the queue of nodes
to visit also added to the set of visited nodes. This is wrong. Queued nodes
aren't visited yet.
Without this fix, there is a possibility of missing metrics.

Fix bug with traversal.

---

src/main/java/org/jenkinsci/plugins/prometheus/service/PrometheusAsyncWorker.java

Fixes noisy log
removes the `Started prometheus_async_worker` and `Finished prometheus_async_worker` from the standard out log. It leads to a lengthly jenkins.log
- override `getNormalLoggingLevel` to set log `Level.Fine`

override `getNormalLoggingLevel` to set log `Level.Fine`

---

pom.xml

Load documentation from Github instead of the wiki.
Related tickets:
https://issues.jenkins-ci.org/browse/WEBSITE-406
https://issues.jenkins-ci.org/browse/JENKINS-59172
More info: https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/

Update pom URL [WEBSITE-406]

---

src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java

Fixes #174 
Make the plugin open for extensions from other plugins.
- [-] Includes tests covering the new functionality? Not sure how to test without creating another plugin
- [/] Ready for review
- [/] Follows CONTRIBUTING rules

Make prometheus plugin open for contributions from other plugins

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

While using #177 in our production instance we found a problem with the stage metrics, only aborted stages are reflected in the metrics. This happened because the stage object use a different status enum than the jobs or runs.
- Use explicit comparison for stage results with the correct enum values

Fix successful stage detection

---

pom.xml
src/test/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfigurationTest.java

System Lambda has minimal impact. It only sets the environment variable
for the statement that reads it. In addition it is independent of the
testing framework. E.g. it can still be used if JUnit 4 is replace with
JUnit Jupiter or another framework.

Replace System Rules with System Lambda

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

Fixes https://issues.jenkins.io/browse/JENKINS-63998. This issue happens, because during gathering of the metrics a NullPointerException occurs when retreiving the job parameters. This exception is not handled, so the thread gathering the metrics is terminated without providing metrics.
Note: This is my first pull-request. If there are any formal issues with it, please tell me.
- Change the way the job parameter string is build, so that a job parameter with a "null" value does not cause a NullPointerException. This seems e.g. to happen for parameterized jobs with a SVN Tags parameter. 

Fix null pointer exception when gathering job parameters (JENKINS-63998)

---

src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java
src/main/java/org/jenkinsci/plugins/prometheus/util/MetricsFormatter.java
src/test/java/org/jenkinsci/plugins/prometheus/util/MetricsFormatterTest.java

Fixes #185 
Heads up - I took a quick look at this and it seems more difficult than I anticipated.
The build node metrics are derived from Dropwizard + jenkins metrics plugin which means we'll either have to:
A) Pull the metric timer out of the jenkins plugin and build a custom metric for it jenkins.node._XXX.builds
B) Intercept the response before it's sent and rewrite those specific endpoints
I went with option B here. It's a bit cleaner.
- Regex Match the specific metric names which include node name
- Standardize metric names and use node name as label
- Add master label to non-node specific metrics
- [/ ] Includes tests covering the new functionality?
- [/ ] Ready for review
- [/ ] Follows CONTRIBUTING rules

Issue 185 - Names & Labels for jenkins_node_*_builds Metrics

---

README.md
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

Fixes #204 
- Add processing of the last completed job, which, we also break down to stages.
- Took the opportunity to unify code between processing a generic run when iterating everything, and when processing the last completed one.
- Added a subclass to handle Run specific metric collectors to make it easier to add more metrics in the future and reduce code duplication
- [V] Ready for review
- [V] Follows CONTRIBUTING rules

ISSUE-204 - last build metrics don't have stages breakdown

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-appendParamLabel.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-appendStatusLabel.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-collectingMetricsPeriodInSeconds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-countAbortedBuilds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-countFailedBuilds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-countNotBuiltBuilds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-countSuccessfulBuilds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-countUnstableBuilds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-defaultNamespace.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-fetchTestResults.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-jobAttributeName.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-processingDisabledBuilds.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-useAuthenticatedEndpoint.jelly
src/test/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfigurationTest.java

Fixes #200 
Fixes #206 
May help address #196 
- I removed the per build metrics introduced in #177.
- I added two new options - "Add build parameter label to metrics" and "Add build status label to metrics".  The purpose of these is to support the use case described in #176. This would allow a user to calculate the average duration of a job based on build parameters or status.  They were left as optional and default to off as build parameters could have a high cardinality.
Screenshot of the new configuration options with their help text:
- I bumped up the minimum required jenkins version.  This seemed to be a requirement of recent dependency updates.  I bumped the version up to what the build spat out as the required minimum version when I tried to run the build.
- I fixed the …

Fix excessive metrics

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/DiskUsageCollector.java

Fixes #246 
- Make Cloudbees Disk Usage Simple plugin an optional dependency.  I've seen disk performance issues when this plugin is enabled, and for my use case I don't need these metrics.  
- This unfortunately does change existing behavior when initially installing the plugin.  Since the Cloudbees Disk Usage Simple plugin isn't required, Jenkins won't automatically install it by default like it would currently.  I couldn't find a way to specify that an optional dependency should be installed by default.  My intention with this change was to allow disabling the disk usage plugin if it wasn't needed, I didn't really want to change the existing behavior on install.
Before change:
After change:
Log message when disk plugin is disabled:

Make cloudbees-disk-usage-simple optional dep

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

Fixes #279
- Enables Jenkins job duration metrics being filterable by build status, thus fixing #279, sorry it took this long to provide the relevant PR
- Note that build fails due to enforcer plugin notifying about some dependencies needing an upgrade; this PR does not cover that error
- [ X ] Ready for review
- [ X ] Follows CONTRIBUTING rules

Fixes #279: Jenkins job duration metrics filterable by buildable status

---

src/main/java/org/jenkinsci/plugins/prometheus/DiskUsageCollector.java
src/test/java/org/jenkinsci/plugins/prometheus/DiskUsageCollectorTest.java

In addition to the storage statistics for folders and jobs, also add metrics about file stores (a.k.a. disks / partitions) on which those folders and jobs are stored.
This adds the two new metrics `file_store_capacity_bytes` and `file_store_available_bytes`, along with the new label `file_store`, that's attached to each folder and job and identifies on which file store they live.

Add metrics about file store usage

---

src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/java/org/jenkinsci/plugins/prometheus/util/ConfigurationUtils.java
src/test/java/org/jenkinsci/plugins/prometheus/util/ConfigurationUtilsTest.java

Fixes [JENKINS-66790](https://issues.jenkins.io/browse/JENKINS-66790)
The `DiskUsageCollector` class uses the `ConfigurationUtils#getCollectDiskUsage` method to determine whether the it should be enabled or not. Unfortunately, the mentioned method ignores the checkbox configuration option available on the `Configure System` page. The `PrometheusConfiguration` class keeps the requested value in the `collectDiskUsage` field. It is calculated based on the saved configuration which fallback to the `COLLECT_DISK_USAGE` environment variable or `true` (if the environment variable is not set). The `ConfigurationUtils#getCollectDiskUsage` method is updated to execute the `PrometheusConfiguration#getCollectDiskUsage()` method, so the user configuration is taken into account.

Disable DiskUsageCollector when its option is unchecked (JENKINS-66790)

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/java/org/jenkinsci/plugins/prometheus/rest/PrometheusAction.java
src/main/java/org/jenkinsci/plugins/prometheus/util/Jobs.java
src/test/java/org/jenkinsci/plugins/prometheus/DiskUsageCollectorTest.java
src/test/java/org/jenkinsci/plugins/prometheus/rest/PrometheusActionTest.java

Fixes broken build.
The project build was broken because the PowerMock libraries version has not been set. However, PowerMock is not compatible with Mockito 3.X, so there is not sense to fix it. Instead the Mockito Inline library is added which supports mocking static methods. The tests were updated to use the new API.
The Jenkins version has been updated to the latest available LTS. Every LTS is provided with a `bom-X.Y.Z` artifact which should be used to determine versions of the most common dependencies (e.g. the `junit` plugin). Whenever the LTS is updated to a newer version, the `bom` artifact must be updated too. All unnecessary dependencies have been removed.
The `Jenkins#getInstance` method is deprecated, so all occurrences have been replaced with `Jenkins#get`. …

Use Mockito Inline instead of PowerMock and cleanup dependencies

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-perBuildMetrics.jelly
src/test/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfigurationTest.java

This basically re-adds the per run metrics initially added with #177 and were removed in #230 
Unfortunately those metrics can easily blow up a Jenkins instance by their sheer number, so this time those metrics are disabled by default and can be enabled (there is a warning in the UI).
The use case for those metrics are short histories of jobs (e.g. having only 10 runs in Jenkins) with their characteristics heavily dependent on parameters and a need to have metrics for a much longer time.
- make it possible to enable per build metrics if desired

Per job metrics

---

src/main/java/org/jenkinsci/plugins/prometheus/util/MetricsFormatter.java
src/test/java/org/jenkinsci/plugins/prometheus/util/MetricsFormatterTest.java

Fixes #375 
Seems like the is a blank required after the comma. Unsure if that fixes the issue completely but on the first deploy on our system it worked.

Possible fix for #375

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/resources/index.jelly

Fixes the hpi build
- Dependabot updated the parent to 4.52 so we need to update to jenkins > 2.361 + java 11 in order to build the hpi file
- [-] Includes tests covering the new functionality?

Fixing hpi build

---

src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-collectDiskUsage.jelly
src/test/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfigurationTest.java

Fixes #482
- The Environment variable COLLECT_DISK_USAGE takes the lead. If it's set to a valid boolean parameter this configuration wins. Otherwise the configured value over the Jenkins configuration page is taken. If the Environment variable is set, then the configuration item in the Jenkins page is disabled. 
@markyjackson-taulia. Do you think that is a valid fix?

Bugfix - Collect Disk Usage is stored correctly

---

docs/metrics/index.md
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/metrics/jobs/CurrentRunDurationGauge.java
src/main/java/org/jenkinsci/plugins/prometheus/util/ArrayUtils.java
src/test/java/org/jenkinsci/plugins/prometheus/metrics/jobs/CurrentRunDurationGaugeTest.java
src/test/java/org/jenkinsci/plugins/prometheus/util/ArrayUtilsTest.java

Fixes #505 
- Adding metric which monitors the runtime of a currently building job run

Adding metric which indicates the runtime of the current build. Can be used to monitor long running jobs

---

src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java

Fixes #563
- only log warning if environment variable exists

Only Log Warning if environment variable is defined and invalid

---

.github/workflows/codacy-analysis.yml
.github/workflows/codeql-analysis.yml
pom.xml

Preparing to test with Java 21 as part of [JENKINS-71800](https://issues.jenkins.io/browse/JENKINS-71800).
Fix Java 21 tests by placing mockito before assertj
[The bytebuddy mailing list](https://groups.google.com/g/byte-buddy/c/H3auRC-SRts/m/7NCRN2wAAwAJ) notes that the version of bytebuddy in assertj does not support Java 21 while the version of bytebuddy in mockito supports Java 21.  Load mockito first so that the newer version of bytebuddy is used for the tests.
This change is **necessary but not sufficient** to pass the tests on Java 21.  The tests run much better on Java 21 with this change, but there are still two tests that fail on both Java 17 and Java 21.  They will need to be investigated and resolved in a separate pull request.
Use plugin BOM to provide metrics and rest API …

Prepare to test Java 21

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/CodeCoverageCollector.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-collectCodeCoverage.jelly

* Removing deprecated coverage-api plugin and using successor plugin
* Using jobAttributeName from configuration instead of "job_name"
Fixes #607

Removing deprecated code-coverage-api plugin dependency and fixing job_name attribute

---

src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java

Fixes https://github.com/jenkinsci/prometheus-plugin/issues/635. It should at least guarantee that loading the extension (that would call the constructor) does register the collector. 
- Initialize PrometheusMetrics after jobs are loaded using `@Initializer`
@Waschndolos

Fix initilization potential deadlock

---

src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildCompletionListener.java
src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildCompletionListenerTest.java

Avoid memory leak when configuring all job count metrics with false

---

src/main/java/org/jenkinsci/plugins/prometheus/context/Context.java
src/main/java/org/jenkinsci/plugins/prometheus/rest/PrometheusAction.java
src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java
src/main/java/org/jenkinsci/plugins/prometheus/service/PrometheusAsyncWorker.java
src/main/java/org/jenkinsci/plugins/prometheus/service/PrometheusMetrics.java
src/test/java/org/jenkinsci/plugins/prometheus/context/ContextTest.java
src/test/java/org/jenkinsci/plugins/prometheus/rest/PrometheusActionTest.java
src/test/java/org/jenkinsci/plugins/prometheus/service/PrometheusAsyncWorkerTest.java

Reverting commits which might cause startup issues on non docker instances

---

src/main/java/org/jenkinsci/plugins/prometheus/DiskUsageCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java

Annotations for Nonnull, CheckForNull, and several others were proposed for Java as part of dormant Java specification request JSR-305. The proposal never became a part of standard Java.
Jenkins plugins should switch from using JSR-305 annotations to use Spotbugs annotations that provide the same semantics.
The [mailing list discussion](https://groups.google.com/g/jenkinsci-dev/c/uE1wwtVi1W0/m/gLxdEJmlBQAJ) from James Nord describes the affected annotations and why they should be replaced with annotations that are actively maintained.
The ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/replace-jsr-305-annotations/) provides instructions to perform this change.
An [OpenRewrite recipe](https://docs.openrewrite.org/recipes/jenkins/javaxannotationstospotbugs …

Replace JSR-305 annotations with spotbugs annotations

---

docs/metrics/index.md
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/CollectorType.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildCollectorFactory.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildLogFileSizeGauge.java
src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildDurationSummaryTestJobTest.java
src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildLogFileSizeGaugeTest.java

Fixes #667
- New Metric which shows the build log size in bytes to detect massive logging in builds

New metrics which shows the build log size in bytes

---

src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java

Fixes #683
- Aynchronously register collectors to prevent blocking Jenkins startup.
@Waschndolos

[#635][#683] Fixing startup problems in certain Jenkins installations

---

docs/metrics/index.md
src/main/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/CollectorType.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/jenkins/JenkinsCollectorFactory.java
src/main/java/org/jenkinsci/plugins/prometheus/collectors/jenkins/JenkinsQuietDownGauge.java
src/test/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollectorTest.java
src/test/java/org/jenkinsci/plugins/prometheus/collectors/jenkins/JenkinsQuietDownGaugeTest.java

This pull request introduces a new "default_jenkins_quietdown" metric to indicate whether Jenkins is in quiet mode.  It can be used to monitor whether Jenkins is processing new jobs.  It uses the Jenkins.isQuietingDown method to determine the status of the server:
- https://javadoc.jenkins.io/jenkins/model/Jenkins.html#isQuietingDown()
This is a fix for Issue #686

Add new metric for Quiet Mode status

---

src/main/java/org/jenkinsci/plugins/prometheus/CodeCoverageCollector.java
src/test/java/org/jenkinsci/plugins/prometheus/CodeCoverageCollectorTest.java

Do not create Collectors for each Job.

---

src/main/java/org/jenkinsci/plugins/prometheus/CodeCoverageCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/DiskUsageCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
src/main/java/org/jenkinsci/plugins/prometheus/config/disabledmetrics/JobRegexDisabledMetric.java
src/main/java/org/jenkinsci/plugins/prometheus/config/disabledmetrics/MetricStatusChecker.java
src/main/resources/org/jenkinsci/plugins/prometheus/config/disabledmetrics/JobRegexDisabledMetric/config.jelly

Fixes  #698
- Adding configuration to exclude certain jobs from metrics output

Adding configuration option to exclude jobs from Prometheus metrics via Regex

---

src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/NbBuildsGauge.java

Avoiding potential deadlock in counting number of builds

---

pom.xml
src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/JobLabel.java
src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
src/main/java/org/jenkinsci/plugins/prometheus/util/ConfigurationUtils.java

- Remove usages of Commons Lang 2
- Ensure to use direct commons-lang3-api instead of transitively via jackson2-api
@Waschndolos

Remove usages of Commons Lang 2
