jenkinsci/prometheus-plugin

- .gitignore
- build.gradle
- settings.gradle
Created basic gradle build scripts so it can also be built with gradle as well as maven.
> added gradle build script

- pom.xml
- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
- src/main/java/org/jenkinsci/plugins/prometheus/util/Runs.java
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
> Enable filtering by build results for build duration export

- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
This made it very hard to set this field via the script console :)
> Fix PrometheusConfiguration.setCountFailedBuilds

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-path.jelly
Also allow empty namespace definition
> allow to configure the default namespace in "Manage Jenkins"

- Jenkinsfile
- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-path.jelly
https://github.com/jenkinsci/prometheus-plugin/commit/8718c444700b1f051a5143ae5d15a4c12adfc680
> Enable automatic build on jenkins.io

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
ref jenkinsci/prometheus-plugin#40
> check configuration for updates on each collection

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Resolving gradle build issues

- src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java
The previous code to abort traversing the node tree when the same node was encountered again didn't actually work which made the plugin unusable for builds with large and complicated node trees.
> stop reparsing the flowNodes

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
> Adding a gauge for the last start time of the build

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
This is a partial fix for issue https://github.com/jenkinsci/prometheus-plugin/issues/10 in that it allows skipping parsing builds completely.
Previously the plugin would parse through all builds and decide for each of them if it should be skipped which potentially takes a lot of time if you have many builds. With this change there is a way to at least get any non build related metrics in a timely fashion.
> don't parse builds if no build duration is to be calculated

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-path.jelly
The per job metrics are not working, I suspect that it is because of the job criteria see https://github.com/jenkinsci/prometheus-plugin/issues/45
> Change name of job to jenkins_job

- README.md
I would like to adopt this plugin. I have placed a post in the Jenkins-dev google group.
> Applying to adopt this plugin

- src/main/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/rest/PrometheusAction.java
- src/main/java/org/jenkinsci/plugins/prometheus/util/ConfigurationUtils.java
> Adding uptime monitor for Jenkins instance

- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
> Add 'public' access modifier to setters to allow CasC configuration

- src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java
- src/test/java/org/jenkinsci/plugins/prometheus/util/FlowNodesTest.java
Fixes #59 
- Instead of looking for StageAction on node, which is never check, check for presence of LabelAction, but no ThreadNameAction
- Updated FlowNodesTest to be consistent
> Identifying Stage Nodes

- pom.xml
> pr [#26](https://github.com/jenkinsci/prometheus-plugin/pull/106)

- src/main/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/MetricsRequest.java
- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
- src/main/java/org/jenkinsci/plugins/prometheus/rest/PrometheusAction.java
- src/main/java/org/jenkinsci/plugins/prometheus/util/Callback.java
- src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java
- src/main/java/org/jenkinsci/plugins/prometheus/util/Jobs.java
- src/main/java/org/jenkinsci/plugins/prometheus/util/Runs.java
This pull request is about code improvements.
I suggest to look at the commits individually as each one addresses a different aspect.
> Code Improvements

- README.md
#129 Added contributing guidelines
> added contributing guidelines

- README.md
added steps to contribute using git bash, it's looking better now!
Fixes #...
- ...
- ...
- ...
> added steps to contribute using git bash

- pom.xml
- src/test/java/org/jenkinsci/plugins/prometheus/rest/PrometheusActionTest.java
When checked out 'mvn clean install' did not build. This addresses the following:
1. Dependency updates to the latest. Due to outdated dependencies and an unspecified Jenkins version, the build would not succeed.
- Specify Jenkins version in pom.xml
- Update slf4j to fix additional build break
- Refactor other dependency version variables for clarity.
- Update all others to latest Jenkins repository version.
2. PrometheusActionTest.java was broken due a conflict with later versions of the JDK
- https://github.com/powermock/powermock/issues/864
- Also updated the test file with some misc hygiene.
- Remove reference to Groovy library.
> Fix build break.

- src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java
When the Prometheus plugin is used on a Jenkins installation with a large number of builds and metrics, it hits the inherent limitations of a recursive algorithm and crashes with a stack overflow. Recursive algorithms are not ideal in production because of this, so rewrite this to be iterative.
Empirical testing has shown that this rewrite fixes the issue and allows Jenkins installations to work and metrics to be scraped properly from Prometheus.
Fixes #127 #128 #134 
- https://issues.jenkins-ci.org/browse/JENKINS-59966
1. Use a standard iterative BFS algorithm.
2. Remove TreeMap for collision purposes (The O(log(n)) sorting of the keys is unncessary) and replace with HashSet.
> Rewrite traverseTree to iterative BFS for scale.

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
Fixes https://github.com/jenkinsci/prometheus-plugin/pull/167#issuecomment-712780595
https://github.com/jenkinsci/prometheus-plugin/pull/167#issuecomment-712780595
- [ no need ] Includes tests covering the new functionality?
- [+] Ready for review
- [+] Follows CONTRIBUTING rules
> change log level to debug

- pom.xml
> adding new dependancy

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/config.jelly
- src/main/resources/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration/help-labeledBuildParameterNames.jelly
- src/test/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfigurationTest.java
Fixes 
https://github.com/jenkinsci/prometheus-plugin/issues/239
- added new plugin attribute labeledBuildParameterNames
> Build parameter as separate metric label

- src/main/java/org/jenkinsci/plugins/prometheus/JenkinsStatusCollector.java
Added the Jenkins Application version to prometheus metrics
- Addition of the Info-Object
- 
> Added Prometheus Info-Object

- README.md
- src/test/java/org/jenkinsci/plugins/prometheus/util/MetricsFormatterTest.java
Reverts jenkinsci/prometheus-plugin#401
> Revert "More reverts"

- .vscode/settings.json
- pom.xml
Reverts jenkinsci/prometheus-plugin#400
> Revert "Linefeed"

- README.md
- docs/metrics/index.md
Fixes #489
Adding documentation about metrics collected by this plugin
> Adding documentation

- src/main/java/org/jenkinsci/plugins/prometheus/config/PrometheusConfiguration.java
Fixes #488 
- Do not call save in setter which is called by constructor
> Calling save in Setter leads to ProvisionException

- docs/metrics/index.md
- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/metrics/BaseMetricCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/metrics/MetricCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/metrics/jobs/BaseJobMetricCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/metrics/jobs/BuildDiscardGauge.java
- src/main/java/org/jenkinsci/plugins/prometheus/metrics/jobs/HealthScoreGauge.java
- src/main/java/org/jenkinsci/plugins/prometheus/metrics/jobs/NbBuildsGauge.java
- src/test/java/org/jenkinsci/plugins/prometheus/metrics/jobs/BuildDiscardGaugeTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/metrics/jobs/CollectorTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/metrics/jobs/HealthScoreGaugeTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/metrics/jobs/JobCollectorTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/metrics/jobs/NbBuildsGaugeTest.java
Adding new base classes to make calculations of values more testable
Fixes #506 
- Future extensions should be done via classes in org/jenkinsci/plugins/prometheus/metrics
-
> Adding NbBuildsGauge which collects the number of available build per job

- src/main/java/org/jenkinsci/plugins/prometheus/CodeCoverageCollector.java
> Fixing log level

- src/main/java/org/jenkinsci/plugins/prometheus/config/disabledmetrics/MetricStatusChecker.java
- src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java
- src/test/java/org/jenkinsci/plugins/prometheus/config/disabledmetrics/MetricStatusCheckerTest.java
Fixes #554
Filter external metrics
> Fixes #554. Apply Metric Filter on all external metrics

- src/main/java/org/jenkinsci/plugins/prometheus/config/disabledmetrics/FilteredMetricEnumeration.java
- src/main/java/org/jenkinsci/plugins/prometheus/service/DefaultPrometheusMetrics.java
- src/test/java/org/jenkinsci/plugins/prometheus/config/disabledmetrics/FilteredMetricEnumerationTest.java
> Fix filtering of external metrics

- src/main/java/org/jenkinsci/plugins/prometheus/DiskUsageCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/CollectorType.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/disk/DiskCollectorFactory.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/disk/DiskUsageFileCountGauge.java
- src/test/java/org/jenkinsci/plugins/prometheus/DiskUsageCollectorTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/disk/DiskUsageFileCountGaugeTest.java
> Add new disk metric for file count

- src/main/java/org/jenkinsci/plugins/prometheus/ExecutorCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/CollectorFactory.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/CollectorType.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildCollectorFactory.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildLikelyStuckGauge.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/JobCollectorFactory.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/LogUpdatedGauge.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildLikelyStuckGaugeTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/jobs/LogUpdatedGaugeTest.java
> Creating Build Metrics for log is updated and build is likely stuck

- README.md
> Updating documentation about scraping the endpoint

- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildResultOrdinalGauge.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildResultOrdinalGaugeTest.java
> Fixing result ordinal when run is currently building

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/StageSummary.java
> Make it possible to get stage statistics per build

- Jenkinsfile
I've made the changes in Jenkinsfile with reference to https://www.jenkins.io/doc/developer/tutorial-improve/add-a-jenkinsfile/
> Corrected Jenkinsfile

- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/CounterManager.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/CounterManagerTest.java
Fixes #615 
* Return a new counter when the namespace is updated
@Waschndolos
> Fix Issue With Namespace Not Updating for Build Counters

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
- Enable incremental for easier testing of PR
I wanted to test https://github.com/jenkinsci/prometheus-plugin/pull/648 but there is no incrementals
See https://www.jenkins.io/doc/developer/tutorial-improve/enable-incrementals/
@Waschndolos
> Enable incrementals for testing PR

- docs/metrics/index.md
> Fixing documentation of default_jenkins_builds__last_build_result

- src/main/java/org/jenkinsci/plugins/prometheus/collectors/disk/DiskUsageBytesGauge.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/disk/DiskUsageFileCountGauge.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/disk/JobUsageBytesGauge.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/disk/DiskUsageBytesGaugeTest.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/disk/JobUsageBytesGaugeTest.java
> Fixing NullPointerException when calculating disk usage

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
to ensure continuous results
Fixes #697
> Calculate last build if job is currently building

- src/test/java/org/jenkinsci/plugins/prometheus/rest/PrometheusActionTest.java
> Migrate from EE 8 to EE 9

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
> Fix: Do not calculate disabled jobs (job counters still do)

- src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/CollectorType.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildCollectorFactory.java
- src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildWaitingDurationGauge.java
- src/test/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildWaitingDurationGaugeTest.java
> New Gauge which displays the waiting time of a run

- pom.xml
Updates the plugin BOM and cleans up the build more generally.
> Update plugin build
